### ISSUE TITLE
Laggy Performance on iOS

### ISSUE THREAD

**Issue by luangm** [homerjam/angular-gsapify-router#13] opened 2015-06-26 17:39 UTC
Hi, I just discovered this through anim-in-out, and I thought it would be a more flexible alternative..
The animation is smooth on PC but slightly laggy in iOS (iphone 6P / iOS 8.2)
As a comparison, using anim-in-out the state-transition anim is smooth.
tested using simple fade-in fade-out defaults, and some basic slide-in-left/right animations.

In particular, the lag seems to occur at the first ~200ms or so, then it's smooth after.
I suspect this is due to competing CPU resources with the actual page-loading controller Javascript codes. Due to JS nature of GSAP. 
Where as CSS3-based transitions do not suffer from this.

One way to replicate this easily is load a Google Map API in the controller synchronously. (i.e. don't use a $timeout). The heavy processing of map loading causes a lot of lag in page transition animations.
(I know this isn't a best practice, just to replicate the symptom).

Any suggestions?

**Comment by homerjam** [comment] 2015-07-01 09:49
Hi,

I think you've nailed what the problem is and why it is `anim-in-out` doesn't suffer the problem so much. Generally I've found performance to be similar except in these instances where there is a significant amount of processing/DOM manipulation happening, unfortunately this is exaggerated on less performant devices.

My workaround for this has been to delay the transition so that it (hopefully) occurs after the DOM has been built etc. Alternatively you can delay the rendering of the heavier elements in your page by using events to trigger them after transitions are finished.

Of course using [transform instead of position](http://www.html5rocks.com/en/tutorials/speed/high-performance-animations/) (left, right, top, bottom) helps. You may like to try the CSS [`will-change`](https://aerotwist.com/blog/bye-bye-layer-hacks/) property.

I use the profiles section of dev tools to figure out where and why some frames exceed the 16ms threshold, this might provide some clarity on where to focus your optimisations.

Hope this helps

James

**Comment by homerjam** [comment] 2015-09-24 16:58
FWIW I've seen this now occurs in OSX Safari too. I'll investigate when I have a moment, let me know if you managed to resolve somehow. Thanks

**Comment by homerjam** [comment] 2016-02-29 11:09
As a partial fix for this I've added an option to delay the transition until a trigger event is fired on the `$rootScope`.

Add the following to your route configuration (in the `data.gsapifyRouter[VIEW_NAME][enter|leave][in|out]`:
```
// add event listener to $rootScope to trigger transition
trigger: 'viewInitialised'
```

Then in your view controller:

```
// broadcast event when view has been initialised
// eg. when expensive layout components/directives have done their thing
$rootScope.$broadcast('viewInitialised');

**Closed** 2018-04-21 00:59 UTC
Labels: help wanted
